services:
  nextjs:
    build: .
    container_name: starsoft_nextjs_app
    ports:
      - "3001:3000"  # Mapeia a porta 3001 no host para a porta 3000 no container
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: yarn dev
